M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date jeu. 07 sept. 2023 14:28:57
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-07T14:28:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X8.3228Y-7.524
X8.3228Y-7.7516
T0
M30
