M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date mar. 11 juil. 2023 09:47:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-11T09:47:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X8.3228Y-7.1303
X8.3228Y-7.3579
T0
M30
